global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  # Prometheus self
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Node Exporter 
  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"] 

  # Microservices
  - job_name: "auth-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8085"]

  - job_name: "user-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user-service:8089"]

  - job_name: "inventory-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["inventory-service:8082"]

  - job_name: "preview-inventory-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["preview-inventory-service:8079"]

  - job_name: "chat-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["chat-service:8090"]

  - job_name: "order-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["order-service:8084"]

  - job_name: "payment-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8086"]

  - job_name: "gateway-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["gateway-service:8083"]

  - job_name: "notification-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8087"]
